defmodule PonteioWeb.SignInLiveTest do
  @moduledoc """
  Smoke test for `GET /sign-in` (issue #3): the route generated by
  `sign_in_route` in the router renders the `:password` strategy's e-mail +
  senha form. The actual authentication behaviour (valid/invalid
  credentials, generic error message) is covered at the resource-action
  level in `Ponteio.Accounts.UserSignInTest`, per SDD §6.
  """

  use PonteioWeb.ConnCase, async: true

  import Phoenix.LiveViewTest

  test "renders the e-mail + password sign-in form", %{conn: conn} do
    {:ok, _lv, html} = live(conn, ~p"/sign-in")

    assert html =~ ~s(type="email")
    assert html =~ ~s(type="password")
  end
end
