defmodule Ponteio.Repo.Migrations.AddChordSegmentsAndSuggestions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:chord_segments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :start_position, :bigint, null: false
      add :end_position, :bigint, null: false
      add :status, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :measure_id,
          references(:measures,
            column: :id,
            name: "chord_segments_measure_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :selected_suggestion_id, :uuid
    end

    create table(:chord_suggestions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:chord_segments) do
      modify :selected_suggestion_id,
             references(:chord_suggestions,
               column: :id,
               name: "chord_segments_selected_suggestion_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end

    alter table(:chord_suggestions) do
      add :base_fret, :bigint, null: false
      add :rank, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :chord_segment_id,
          references(:chord_segments,
            column: :id,
            name: "chord_suggestions_chord_segment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :chord_shape_id,
          references(:chord_shapes,
            column: :id,
            name: "chord_suggestions_chord_shape_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:chord_suggestions, "chord_suggestions_chord_shape_id_fkey")

    drop constraint(:chord_suggestions, "chord_suggestions_chord_segment_id_fkey")

    alter table(:chord_suggestions) do
      remove :chord_shape_id
      remove :chord_segment_id
      remove :updated_at
      remove :inserted_at
      remove :rank
      remove :base_fret
    end

    drop constraint(:chord_segments, "chord_segments_selected_suggestion_id_fkey")

    drop constraint(:chord_segments, "chord_segments_measure_id_fkey")

    alter table(:chord_segments) do
      modify :selected_suggestion_id, :uuid
    end

    drop table(:chord_suggestions)

    drop table(:chord_segments)
  end
end
