defmodule Ponteio.Repo.Migrations.CreateTablatures do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:measures, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :position, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tab_id, :uuid, null: false
    end

    create index(:measures, [:tab_id, :position])

    create table(:notes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :position, :bigint, null: false
      add :string, :bigint, null: false
      add :fret, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :measure_id,
          references(:measures,
            column: :id,
            name: "notes_measure_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create index(:notes, [:measure_id, :position])

    create table(:tabs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:measures) do
      modify :tab_id,
             references(:tabs,
               column: :id,
               name: "measures_tab_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:tabs) do
      add :title, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:tabs) do
      remove :updated_at
      remove :inserted_at
      remove :title
    end

    drop constraint(:measures, "measures_tab_id_fkey")

    alter table(:measures) do
      modify :tab_id, :uuid
    end

    drop table(:tabs)

    drop_if_exists index(:notes, [:measure_id, :position])

    drop constraint(:notes, "notes_measure_id_fkey")

    drop table(:notes)

    drop_if_exists index(:measures, [:tab_id, :position])

    drop table(:measures)
  end
end
