defmodule Ponteio.Repo.Migrations.AddChordShapes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:chord_shapes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :slug, :text, null: false
      add :name, :text, null: false
      add :quality, :text, null: false
      add :root_string, :bigint, null: false
      add :relative_frets, {:array, :bigint}, null: false
      add :movable, :boolean, null: false, default: false
      add :min_base_fret, :bigint, null: false, default: 0
      add :max_base_fret, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:chord_shapes, [:slug], name: "chord_shapes_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:chord_shapes, [:slug], name: "chord_shapes_unique_slug_index")

    drop table(:chord_shapes)
  end
end
